services:
    beets-flask:
        image: ghcr.io/matthieudecamy/beets-flask:latest
        container_name: shlagi-tagger
        restart: unless-stopped
        ports:
            - "5006:5001"
        environment:
            TZ: "Europe/Paris"
            USER_ID: 1026
            GROUP_ID: 100
        volumes:
            - /volume1/docker/Music/beets-flask/config:/config
            # for music folders, paths match inside and out of container!
            - /volume1/docker/Music/MusicToTag:/volume1/docker/Music/MusicToTag
            - /volume1/docker/Music/Music:/volume1/docker/Music/Music
